spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   username: root
   password: 123456
   url: jdbc:mysql://192.168.1.129/sell?characterEncoding=utf-8&useSSL=false
 jpa:
   show-sql: true
   hibernate:
     ddl-auto: update
 jackson:
   default-property-inclusion: non_null
 redis:
   host: 192.168.1.129
   port: 6379
#   password:   这里没有设置密码所以不用配置 如果在redis中配置了密码 这里就需要配置

#设置项目根路径
server:
  context-path: /sell

wechat:
  mpAppId: wx1210394b7c7e7def
  mpAppSecret: 4f55cc620ce39249819b0449dfa9a76d
  mchId: 1409146202
  mcKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://127.0.0.1:8080
  wechatOpenAuthorize: http://127.0.0.1:8080
  sell: http://127.0.0.1:8080
  #  注意加上http://前缀 否则就不是 完成跳转 而是在之前的URL后面加上 再进行跳转
#  设置mybatis对应包中的查看路径，方便调试查看sql语句
logging:
  level:
    com.cherry.dataobject.mapper: trace
#    mybatis xml配置方式的扫描路径配置 classpath就是resources路径
mybatis:
  mapper-locations: classpath:mapper/*.xml



